import { chromium } from 'playwright'
const browser = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true })
const page = await browser.newPage({ viewport: { width: 1560, height: 1000 }, locale: 'zh-CN' })
await page.goto('http://127.0.0.1:3080/', { waitUntil: 'domcontentloaded' })
await page.waitForTimeout(6000)
await page.getByTestId('yzj-dock-home').click().catch(() => {})
await page.waitForTimeout(2000)
await page.getByTestId('yzj-workbench-tabs').getByRole('tab', { name: '推进' }).click()
await page.waitForTimeout(4500)
const toggle = page.getByTestId('yzj-advance-closed-toggle')
console.log('closed toggle:', await toggle.innerText().catch(() => 'MISSING'))
await toggle.click()
await page.waitForTimeout(800)
await page.screenshot({ path: '/Users/guoxinshan/dev/dsh-yzj/.acceptance/shots-advance-ux/audit-3-closed.png' })
// 点终局探针进详情 → 终局提示
await page.getByText(/终局探针/).first().click()
await page.waitForTimeout(3500)
const terminal = page.getByTestId('yzj-advance-terminal')
console.log('terminal hint after open closed item:', await terminal.count() > 0 ? 'PASS' : 'FAIL')
await page.screenshot({ path: '/Users/guoxinshan/dev/dsh-yzj/.acceptance/shots-advance-ux/audit-4-closed-detail.png' })
await browser.close()
