import { chromium } from 'playwright'
const browser = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true })
const page = await browser.newPage({ viewport: { width: 1560, height: 1000 }, locale: 'zh-CN' })
await page.goto('http://127.0.0.1:3080/', { waitUntil: 'domcontentloaded' })
await page.waitForTimeout(6000)
await page.getByTestId('yzj-dock-home').click().catch(() => {})
await page.waitForTimeout(2000)
await page.getByTestId('yzj-workbench-tabs').getByRole('tab', { name: '推进' }).click()
await page.waitForTimeout(4500)
await page.getByTestId('yzj-advance-pane').getByText(/测试事项/).first().click()
await page.waitForTimeout(4000)
await page.screenshot({ path: '/Users/guoxinshan/dev/dsh-yzj/.acceptance/shots-advance-ux/ux-redesign.png' })
await browser.close()
console.log('shot done')
