// ops daemon wrapper (generated by scripts/setup-ops.mjs; safe to edit).
// Spawned detached by robot-yzj autostart / ops-daemon.cmd / start-all.cmd.
// Starts the base-only dsh-routines scheduler and records its pid in
// <DSH_HOME>/ops.pid so every launch path is idempotent. The wrapper itself
// exits immediately; the daemon keeps running (detached), and a stale pid
// file is simply overwritten on the next launch.
import { spawn } from 'node:child_process'
import { writeFileSync, rmSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'

const home = process.env.DSH_HOME ?? join(homedir(), '.dsh')
const pidFile = join(home, 'ops.pid')

const child = spawn(
  process.execPath,
  ['--import', 'tsx/esm', 'apps/cli/src/bin.ts', '--profile', 'ops'],
  { cwd: process.cwd(), stdio: 'ignore', detached: true },
)
writeFileSync(pidFile, String(child.pid ?? ''), 'utf8')
child.unref()
for (const event of ['exit', 'error']) {
  child.on(event, () => {
    try { rmSync(pidFile, { force: true }) } catch { /* best-effort */ }
  })
}
