#!/usr/bin/env node
/**
 * One-shot ops-daemon bootstrap (dsh-routines scheduler + chatnode bridge client).
 *
 * The bundle ships the bridge contract (robot-yzj provides ctx.chatnode in
 * bridge-client mode) but the SCHEDULER is an external plugin
 * (github:Jesse-njx/dsh-routines) that must run in a base-only profile — the
 * web profile has no job controller and would crash on every tick. This
 * script assembles that profile from your environment:
 *
 *   1. `dsh plugin --profile ops add github:Jesse-njx/dsh-routines`
 *   2. writes profiles/ops/cordis.patch.yml (routines-store/scheduler +
 *      an inserted robot-yzj bridge-client row)
 *   3. links @deepseek-ai peers from the harness checkout (registry rc.6
 *      ranges would drift from the local harness; link: keeps one copy)
 *   4. writes the dsh-run.mjs spawn wrapper and a routine YAML template
 *
 * Usage: node scripts/setup-ops.mjs <options>
 *   --harness <dir>    harness checkout root (default: ../deepseek-harness)
 *   --home <dir>       DSH home (default: $DSH_HOME or ~/.dsh)
 *   --bridge-target <url>  chatnode bridge listener (default: http://127.0.0.1:3080/yzj/chatnode)
 *   --bridge-token <token> shared secret; when omitted, printed and stored in <home>/bridge-token.txt
 *   --robot-yzj <path> robot-yzj package root (default: this repo root — the monobundle)
 *   --cwd <dir>        routines project anchor (default: OS home)
 *   --only <step>      run a single step: profile | peers | wrapper | routine
 *
 * The bridge LISTENER (web profile) is configured separately: add
 * `bridgeToken` + `chatnodeRobotIndex` to the robot-yzj row of the web
 * profile patch (see docs/spec/routines-delivery.md §6).
 */
import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const REPO = fileURLToPath(new URL('..', import.meta.url))
const DSH_CLI = 'apps/cli/src/bin.ts'
const PEERS = [
  ['@deepseek-ai/cordis', 'vendor/cordis'],
  ['@deepseek-ai/cordis-plugin-timer', 'vendor/timer'],
  ['@deepseek-ai/dsh-agent', 'packages/core/agent'],
  ['@deepseek-ai/dsh-agent-default-model', 'packages/core/agent-default-model'],
  ['@deepseek-ai/dsh-cmdline', 'packages/boot/cmdline'],
  ['@deepseek-ai/dsh-jobs', 'packages/jobs/jobs'],
  ['@deepseek-ai/dsh-llm', 'packages/llm/llm'],
  ['@deepseek-ai/dsh-session', 'packages/core/session'],
  ['@deepseek-ai/schemastery', 'vendor/schemastery'],
]

function arg(name, fallback) {
  const at = process.argv.indexOf(`--${name}`)
  return at >= 0 && process.argv[at + 1] !== undefined ? process.argv[at + 1] : fallback
}
function flag(name) {
  return process.argv.includes(`--${name}`)
}

const harness = resolve(arg('harness', join(REPO, '..', 'deepseek-harness')))
const home = resolve(arg('home', process.env.DSH_HOME ?? join(homedir(), '.dsh')))
const bridgeTarget = arg('bridge-target', 'http://127.0.0.1:3080/yzj/chatnode')
const tokenFile = join(home, 'bridge-token.txt')
const bridgeToken = arg('bridge-token', existsSync(tokenFile) ? readFileSync(tokenFile, 'utf8').trim() : '')
const profileDir = join(home, 'profiles', 'ops')
const routinesDir = join(home, 'routines')
const cwd = resolve(arg('cwd', homedir()))
const only = arg('only', '')
const bin = process.execPath

function dsh(args) {
  execFileSync(bin, ['--import', 'tsx/esm', join(harness, DSH_CLI), ...args], {
    cwd: harness,
    stdio: 'inherit',
    env: { ...process.env, DSH_HOME: home },
  })
}

function step(name, fn) {
  if (only !== '' && only !== name) return
  console.log(`\n== ${name} ==`)
  fn()
}

step('profile', () => {
  dsh(['plugin', '--profile', 'ops', 'add', 'github:Jesse-njx/dsh-routines'])
  const patch = `# ops daemon profile (generated by scripts/setup-ops.mjs; safe to edit).
# dsh-routines scheduler + chatnode bridge client. Runs boot the headless
# profile as one-shot subprocesses; digests deliver through the web profile's
# /yzj/chatnode bridge listener.
- id: routines-store
  config:
    projectDir: ${JSON.stringify(cwd)}
- id: routines-scheduler
  config:
    dshBin: ${JSON.stringify(join(home, 'dsh-run.mjs'))}
    runModule: file:///${join(profileDir, 'node_modules', '@dsh-routines', 'bundle', 'lib', 'run.js').replaceAll('\\', '/')}
    tickIntervalMs: 15000
    digestMaxChars: 8000
- insert:
    - id: robot-yzj
      name: '@dsh-yzj/bundle/robot-yzj'
      config:
        bridgeTarget: ${JSON.stringify(bridgeTarget)}
        bridgeToken: ${JSON.stringify(bridgeToken)}
`
  mkdirSync(profileDir, { recursive: true })
  writeFileSync(join(profileDir, 'cordis.patch.yml'), patch, 'utf8')
  console.log(`wrote ${join(profileDir, 'cordis.patch.yml')}`)
})

step('peers', () => {
  // Harness-checkout links keep one @deepseek-ai copy (registry rc.6 ranges
  // would drift from the local checkout; see docs/release.md).
  const specs = PEERS.map(([, rel]) => `link:${join(harness, rel)}`)
  const pnpmBin = process.platform === 'win32' ? 'pnpm.cmd' : 'pnpm'
  // .cmd shims refuse direct spawn since the CVE-2024-27980 hardening; the
  // specs are machine-generated link: paths with no shell metacharacters.
  execFileSync(pnpmBin, ['add', ...specs], { cwd: profileDir, stdio: 'inherit', shell: process.platform === 'win32' })
})

step('wrapper', () => {
  const wrapper = `// dsh-routines run wrapper (generated by scripts/setup-ops.mjs).
// realSpawn launches this .mjs via node; the harness CLI entry is TS source
// and must run under tsx with the harness checkout as cwd.
import { spawn } from 'node:child_process'

const HARNESS = ${JSON.stringify(harness)}

const child = spawn(
  process.execPath,
  ['--import', 'tsx/esm', 'apps/cli/src/bin.ts', ...process.argv.slice(2)],
  { cwd: HARNESS, stdio: 'inherit', env: process.env },
)
child.on('exit', (code, signal) => process.exit(code ?? (signal === null ? 0 : 1)))
child.on('error', (error) => { console.error('dsh-run wrapper: ' + error.message); process.exit(1) })
`
  writeFileSync(join(home, 'dsh-run.mjs'), wrapper, 'utf8')
  // ops daemon wrapper: pid-file idempotent; spawned by robot-yzj autostart,
  // ops-daemon.cmd, or start-all.cmd (see scripts/ops-wrapper.mjs template).
  const opsWrapper = readFileSync(join(REPO, 'scripts', 'ops-wrapper.mjs'), 'utf8')
  writeFileSync(join(home, 'ops-wrapper.mjs'), opsWrapper, 'utf8')
  const daemonCmd = `@echo off
rem dsh-ops-daemon launcher (generated by scripts/setup-ops.mjs). IDEMPOTENT via
rem the pid file: a live pid means the daemon is already up (re-running the
rem startup-folder copy, start-all.cmd, or this file never double-starts).
set PIDFILE=%USERPROFILE%\\.dsh\\ops.pid
if exist "%PIDFILE%" (
  set /p OLDPID=<"%PIDFILE%"
  tasklist /fi "PID eq %OLDPID%" 2>nul | findstr "%OLDPID%" >nul && (
    echo dsh-ops-daemon already running ^(pid %OLDPID%^).
    exit /b 0
  )
)
cd /d ${JSON.stringify(harness).replaceAll('"', '')}
start "dsh-ops-daemon" /min cmd /c "node ${JSON.stringify(join(home, 'ops-wrapper.mjs')).replaceAll('"', '')}"
`
  writeFileSync(join(home, 'ops-daemon.cmd'), daemonCmd, 'utf8')
  const startAll = `@echo off
rem Login autostart for the full production stack (generated by setup-ops.mjs):
rem ops scheduler daemon (background, idempotent) + web GUI (minimized).
call "%USERPROFILE%\\.dsh\\ops-daemon.cmd"
cd /d ${JSON.stringify(harness).replaceAll('"', '')}
start "dsh-web-gui" /min cmd /c "node --import tsx/esm apps/cli/src/bin.ts web"
`
  writeFileSync(join(home, 'start-all.cmd'), startAll, 'utf8')
  console.log(`wrote ${join(home, 'dsh-run.mjs')}, ops-wrapper.mjs, ops-daemon.cmd, start-all.cmd`)
})

step('routine', () => {
  const sample = `# 定时链路巡检样例（generated by scripts/setup-ops.mjs）。
# 每 5 分钟跑一次，确认 ops 调度器 → headless run → 桥 → 群机器人投递全链路正常。
# 改 prompt/schedule 即改行为；\`dsh routines pause <name>\` 可暂停（ops profile 下执行）。
name: c11-prod
schedule: every 5m
timezone: Asia/Shanghai
profile: headless
cwd: ${JSON.stringify(cwd)}
overlap: skip
timeoutMin: 10
deliver:
  - type: file
  - type: chatnode
prompt: |
  你是无人值守定时巡检。一句话确认：dsh 定时任务链路正常，当前无异常需要处理。
  不要调用任何工具，直接简短回复。
`
  mkdirSync(routinesDir, { recursive: true })
  writeFileSync(join(routinesDir, 'c11-prod.yaml'), sample, 'utf8')
  console.log(`wrote ${join(routinesDir, 'c11-prod.yaml')}`)
})

if (!flag('no-token') && bridgeToken === '') {
  const crypto = await import('node:crypto')
  const token = crypto.randomBytes(24).toString('hex')
  writeFileSync(tokenFile, token, 'utf8')
  console.log(`\nbridge token: ${token} (stored ${tokenFile})`)
  console.log('Add the SAME token as bridgeToken to the web profile robot-yzj row.')
}

if (only === '') {
  console.log(`
Done. Next steps:
  1. web profile: add bridgeToken + chatnodeRobotIndex to the robot-yzj row
     (same token as above), then restart the GUI;
  2. seed the scheduler:  dsh --profile ops routines run c11-prod
     (a fresh 'every Nm' state never self-triggers; see docs/pitfalls/pitfall-009);
  3. keep it alive: start-prod.cmd or a login-autostart copy of ops-daemon.cmd
     (both under ${home}/; the launcher is idempotent).
`)
}
